name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:

  ci_cd:
    name: Build, test and deploy
    runs-on: ubuntu-22.04

    steps:
    - name: 01 - Checkout
      uses: actions/checkout@v3

    - name: 02 - Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: 03 - Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'pnpm'

    - name: 04 - Install dependencies
      run: HUSKY=0 pnpm install --no-frozen-lockfile

    - name: 05 - Build application
      run: pnpm build

    # - name: 06 - Creating .npmrc
    #   run: |
    #       echo "@lucasvtiradentes:registry=https://npm.pkg.github.com" >> .npmrc
    #       echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    # - name: 07 - Create Release Pull Request or Publish to npm
    #   id: changesets
    #   uses: changesets/action@v1
    #   with:
    #     publish: pnpm publish:publish
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
